import os
import time
from flask import Blueprint, request, jsonify

recipe_bp = Blueprint('recipe_bp', __name__)

# Hard-coded Demo Data
DEMO_INGREDIENTS = ["bread", "peanut butter", "jelly"]
DEMO_RECIPE = {
    "title": "Budget-Friendly PB&J",
    "instructions": [
        "1. Lay out two slices of bread.",
        "2. Spread peanut butter on one slice.",
        "3. Spread jelly on the other slice.",
        "4. Press slices together and enjoy."
    ],
    "cost_estimate": "$0.75",
    "cooking_method": "No-cook / Prep only"
}

def run_cv_model(image_path):
    """Simulates the Computer Vision identification[cite: 17, 18]."""
    # For the demo, we return the specific items needed for PB&J
    return ["bread", "peanut butter", "jelly"]

@recipe_bp.route('/generate-recipe', methods=['POST'])
def generate_recipe():
    start_time = time.time()
    
    if 'image' not in request.files:
        return jsonify({"error": "No image provided"}), 400

    image = request.files['image']
    temp_path = f"temp_demo_{image.filename}"
    image.save(temp_path)

    try:
        # 1. Image Analyzer: CV identifies ingredients [cite: 17, 39]
        ingredients = run_cv_model(temp_path)
        
        # 2. Privacy: Delete raw image immediately after processing
        if os.path.exists(temp_path):
            os.remove(temp_path)

        # 3. Demo Logic: If it's our PB&J ingredients, return the hard-coded recipe
        if set(ingredients) == set(DEMO_INGREDIENTS):
            recipe = DEMO_RECIPE
        else:
            # Fallback for non-demo items (to be replaced by LLM later) [cite: 22, 29]
            recipe = {
                "title": "Generic Budget Meal",
                "instructions": "Instructions would be generated by LLM here.",
                "cost_estimate": "Varies"
            }

        # 4. Success Metric: Ensure response is under 10 seconds
        total_time = time.time() - start_time
        
        return jsonify({
            "success": True,
            "detected_ingredients": ingredients,
            "recipe": recipe,
            "processing_time": f"{total_time:.2f}s",
            "source": "Demo-Hardcoded"
        }), 200

    except Exception as e:
        # Fail safely and display error message
        if os.path.exists(temp_path):
            os.remove(temp_path)
        return jsonify({"error": "An error occurred during processing."}), 500
